src/SSRSCore.Modules/SSRSCore.Workflows/Controllers/ActivityController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.Extensions.Localization;
using SSRSCore.Admin;
using SSRSCore.DisplayManagement;
using SSRSCore.DisplayManagement.ModelBinding;
using SSRSCore.DisplayManagement.Notify;
using SSRSCore.Settings;
using SSRSCore.Workflows.Models;
using SSRSCore.Workflows.Services;
using SSRSCore.Workflows.ViewModels;
using YesSql;

namespace SSRSCore.Workflows.Controllers
{
    [Admin]
    public class ActivityController : Controller, IUpdateModel
    {
        private readonly ISession _session;
        private readonly IActivityLibrary _activityLibrary;
        private readonly IWorkflowManager _workflowManager;
        private readonly IActivityIdGenerator _activityIdGenerator;
        private readonly IAuthorizationService _authorizationService;
        private readonly IActivityDisplayManager _activityDisplayManager;
        private readonly INotifier _notifier;

        private dynamic New { get; }
        private IStringLocalizer S { get; }
        private IHtmlLocalizer H { get; }

        public ActivityController
        (
            ISession session,
            IActivityLibrary activityLibrary,
            IWorkflowManager workflowManager,
            IActivityIdGenerator activityIdGenerator,
            IAuthorizationService authorizationService,
            IActivityDisplayManager activityDisplayManager,
            IShapeFactory shapeFactory,
            INotifier notifier,
            IStringLocalizer<ActivityController> s,
            IHtmlLocalizer<ActivityController> h
        )
        {
            _session = session;
            _activityLibrary = activityLibrary;
            _workflowManager = workflowManager;
            _activityIdGenerator = activityIdGenerator;
            _authorizationService = authorizationService;
            _activityDisplayManager = activityDisplayManager;
            _notifier = notifier;

            New = shapeFactory;
            S = s;
            H = h;
        }

        public async Task<IActionResult> Create(string activityName, int workflowTypeId, string returnUrl)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageWorkflows))
            {
                return Unauthorized();
            }

            var activity = _activityLibrary.InstantiateActivity(activityName);
            var activityId = _activityIdGenerator.GenerateUniqueId(new ActivityRecord());
            var activityEditor = await _activityDisplayManager.BuildEditorAsync(activity, this, isNew: true);

            activityEditor.Metadata.Type = "Activity_Edit";

            var viewModel = new ActivityEditViewModel
            {
                Activity = activity,
                ActivityId = activityId,
                ActivityEditor = activityEditor,
                WorkflowTypeId = workflowTypeId,
                ReturnUrl = returnUrl
            };

            if (!activity.HasEditor)
            {
                // No editor to show; short-circuit to the "POST" action.
                return await Create(activityName, viewModel);
            }

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(string activityName, ActivityEditViewModel model)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageWorkflows))
            {
                return Unauthorized();
            }

            var workflowType = await _session.GetAsync<WorkflowType>(model.WorkflowTypeId);
            var activity = _activityLibrary.InstantiateActivity(activityName);
            var activityEditor = await _activityDisplayManager.UpdateEditorAsync(activity, this, isNew: true);

            if (!ModelState.IsValid)
            {
                activityEditor.Metadata.Type = "Activity_Edit";
                model.Activity = activity;
                model.ActivityEditor = activityEditor;
                return View(model);
            }

            var activityRecord = new ActivityRecord
            {
                ActivityId = model.ActivityId,
                Name = activity.Name,
                Properties = activity.Properties,
            };
            workflowType.Activities.Add(activityRecord);

            _session.Save(workflowType);
            _notifier.Success(H["Activity added successfully"]);

            return Url.IsLocalUrl(model.ReturnUrl) ? (IActionResult)Redirect(model.ReturnUrl) : RedirectToAction("Edit", "WorkflowType", new { id = model.WorkflowTypeId });
        }

        public async Task<IActionResult> Edit(int workflowTypeId, string activityId, string returnUrl)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageWorkflows))
            {
                return Unauthorized();
            }

            var workflowType = await _session.GetAsync<WorkflowType>(workflowTypeId);
            var activityRecord = workflowType.Activities.Single(x => x.ActivityId == activityId);
            var activityContext = await _workflowManager.CreateActivityExecutionContextAsync(activityRecord, activityRecord.Properties);
            var activityEditor = await _activityDisplayManager.BuildEditorAsync(activityContext.Activity, this, isNew: false);

            activityEditor.Metadata.Type = "Activity_Edit";

            var viewModel = new ActivityEditViewModel
            {
                Activity = activityContext.Activity,
                ActivityId = activityId,
                ActivityEditor = activityEditor,
                WorkflowTypeId = workflowTypeId,
                ReturnUrl = returnUrl
            };

            return View("EditActivity", viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ActivityEditViewModel model)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageWorkflows))
            {
                return Unauthorized();
            }

            var workflowType = await _session.GetAsync<WorkflowType>(model.WorkflowTypeId);
            var activityRecord = workflowType.Activities.Single(x => x.ActivityId == model.ActivityId);
            var activityContext = await _workflowManager.CreateActivityExecutionContextAsync(activityRecord, activityRecord.Properties);
            var activityEditor = await _activityDisplayManager.UpdateEditorAsync(activityContext.Activity, this, isNew: false);

            if (!ModelState.IsValid)
            {
                activityEditor.Metadata.Type = "Activity_Edit";
                model.Activity = activityContext.Activity;
                model.ActivityEditor = activityEditor;

                return View("EditActivity", model);
            }

            activityRecord.Properties = activityContext.Activity.Properties;

            _session.Save(workflowType);
            _notifier.Success(H["Activity updated successfully"]);

            return Url.IsLocalUrl(model.ReturnUrl)
                ? (IActionResult)Redirect(model.ReturnUrl)
                : RedirectToAction("Edit", "WorkflowType", new { id = model.WorkflowTypeId });
        }
    }
}

src/SSRSCore.Modules/SSRSCore.Workflows/Views/Activity.Design.cshtml
@using SSRSCore.Workflows.Models
@using SSRSCore.Workflows.Activities
@{
    var activityRecord = (ActivityRecord)Model.ActivityRecord;
    var activity = (IActivity)Model.Activity;
    var activityEvent = activity as IEvent;
    var isEvent = activityEvent != null;
    var isStart = activityRecord.IsStart;
    var cssClass = isStart ? "activity-start" : isEvent ? "activity-event" : "activity-task";
    var hasEditor = activity.HasEditor;
    var activityType = isEvent ? "Event" : "Task";
    var activityTypeClass = isEvent ? "fa-bolt" : "fa-caret-right";
}
<div class="activity @cssClass" style="left:@(activityRecord.X)px; top:@(activityRecord.Y)px;" id="@($"activity-{Model.WorkflowTypeId}-{activityRecord.ActivityId}")" data-activity-id="@activityRecord.ActivityId" data-activity-start="@isStart.ToString().ToLower()" data-activity-type="@activityType" data-activity-has-editor="@hasEditor.ToString().ToLower()" data-placement="bottom">
    @await DisplayAsync(Model.Content)
    @if (isEvent)
    {
        <div class="clearfix">
            <div class="float-right">
                <i class="fa @activityTypeClass"></i>
            </div>
        </div>
    }
    <div class="activity-commands">
        <a class="btn btn-outline-secondary activity-start-action" href="#" data-toggle="button" title="@T["Startup task"]"><i class="fa fa-power-off"></i></a>
        @if (hasEditor)
        {
            <a class="btn btn-primary activity-edit-action" asp-action="Edit" asp-controller="Activity" asp-route-workflowtypeid="@Model.WorkflowTypeId" asp-route-activityid="@activityRecord.ActivityId" asp-route-returnurl="@Model.ReturnUrl" data-persist-workflow="true" title="@T["Edit"]"><i class="fa fa-pencil"></i></a>
        }
        <a class="btn btn-danger activity-delete-action" href="#" title="@T["Delete"]"><i class="fa fa-trash"></i></a>
    </div>
</div>

src/SSRSCore.Modules/SSRSCore.Workflows/Views/Activity.DesignReadonly.cshtml
@using SSRSCore.Workflows.Models
@using SSRSCore.Workflows.Activities
@{
    var activityRecord = (ActivityRecord)Model.ActivityRecord;
    var activity = (IActivity)Model.Activity;
    var activityEvent = activity as IEvent;
    var isEvent = activityEvent != null;
    var isBlocking = (bool)Model.IsBlocking;
    var activityType = isEvent ? "Event" : "Task";
    var activityTypeClass = isEvent ? "fa-bolt" : "fa-caret-right";
    var cssClass = isBlocking ? "activity-blocking" : isEvent ? "activity-event" : "activity-task";
}
<div class="activity @cssClass" style="left:@(activityRecord.X)px; top:@(activityRecord.Y)px;" id="@($"activity-{Model.WorkflowTypeId}-{activityRecord.ActivityId}")" data-activity-id="@activityRecord.ActivityId" data-activity-type="@activityType">
    @await DisplayAsync(Model.Content)
    @if (isEvent)
    {
        <div class="clearfix">
            <div class="float-right">
                <i class="fa @activityTypeClass"></i>
            </div>
        </div>
    }
</div>

src/SSRSCore.Modules/SSRSCore.Workflows/Views/Activity.Edit.cshtml
@await DisplayAsync(Model.Content)

src/SSRSCore.Modules/SSRSCore.Workflows/Views/Activity.Thumbnail.cshtml
@using SSRSCore.Workflows.Activities;
@using SSRSCore.Workflows.Helpers;
@model dynamic
@{
    var activity = (IActivity)Model.Activity;
    var isEvent = activity.IsEvent();
    var activityType = isEvent ? "Event" : "Task";
}
<div class="card activity" data-category="@activity.Category.Name.HtmlClassify()" data-activity-type="@activityType">
    <div class="card-body">
        @await DisplayAsync(Model.Content)
    </div>
    <div class="card-footer text-muted text-xs-right">
        <a class="btn btn-primary btn-sm" asp-route-action="Create" asp-route-controller="Activity" asp-route-activityname="@activity.Name" asp-route-workflowtypeid="@Model.WorkflowTypeId" asp-route-returnurl="@Model.ReturnUrl" data-persist-workflow="true">@T["Add"]</a>
    </div>
</div>

src/SSRSCore.Modules/SSRSCore.Workflows/Views/ActivityMetadata.Edit.cshtml
@using SSRSCore.Workflows.ViewModels;
@model ActivityMetadataEditViewModel

<fieldset class="form-group" asp-validation-class-for="Title">
    <label asp-for="Title">@T["Title"]</label>
    <input type="text" asp-for="Title" class="form-control" />
    <span asp-validation-for="Title"></span>
    <span class="hint">@T["Optionally provide a custom title for this activity."]</span>
</fieldset>

src/SSRSCore.Modules/SSRSCore.Workflows/Views/Content.UserTaskButton.cshtml
@using SSRSCore.Workflows.UserTasks.ViewModels
@model UserTaskEventContentViewModel
@{
    var actions = Model.Actions;
}
@if (actions.Count <= 2)
{
    @foreach (var action in actions)
    {
        <button type="submit" name="submit.Save" class="btn btn-warning" value="user-task.@action">@T[action]</button>
    }
}
else
{
    <div class="btn-group" role="group">
        <button id="userActionsButtonGroup" type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @T["User Actions"]
        </button>
        <div class="dropdown-menu" aria-labelledby="userActionsButtonGroup">
            @foreach (var action in actions)
            {
                <button type="submit" name="submit.Save" class="dropdown-item" value="user-task.@action">@T[action]</button>
            }
        </div>
    </div>
}

src/SSRSCore.Modules/SSRSCore.Workflows/Views/NavigationItemText-workflows.Id.cshtml
<span class="icon"><i class="fa fa-sitemap fa-rotate-270" aria-hidden="true"></i></span><span class="title">@T["Workflows"]</span>